repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict

  # UV for dependency management
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.13
    hooks:
      # Ensure uv.lock is up-to-date
      - id: uv-lock
        args: [--locked]
        files: pyproject.toml
      # Export requirements for compatibility
      - id: uv-export
        args: [--frozen, --no-hashes, --output-file=requirements.txt]
        files: pyproject.toml|uv.lock
      # Export dev requirements
      - id: uv-export
        name: Export dev requirements
        args: [--frozen, --no-hashes, --all-extras, --output-file=requirements-dev.txt]
        files: pyproject.toml|uv.lock

  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: \.py$
      - id: ruff-format
        files: \.py$

  # MyPy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [types-pyyaml, types-requests, types-toml]
        args: [--ignore-missing-imports, --strict]
        exclude: ^(tests/|tree-sitter-bash/)
        files: \.py$

  # Deptry for dependency checking
  - repo: https://github.com/fpgmaas/deptry
    rev: 0.23.0
    hooks:
      - id: deptry
        args: [src, --config, pyproject.toml]

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict, -c, .yamllint.yml]
        exclude: ^(tree-sitter-bash/|node_modules/)

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [--severity=error, --extended-analysis=true]
        exclude: ^(tree-sitter-bash/|node_modules/)

  # Actionlint for GitHub Actions
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  # Commitizen for commit message validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
