# Minimal Prefect configuration for testing
active = "default"

[profiles.default]
name = "default"
PREFECT_SERVER_ALLOW_EPHEMERAL_MODE = false

[profiles.ephemeral]
name = "ephemeral"
PREFECT_SERVER_ALLOW_EPHEMERAL_MODE = true
