name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for pre-commit hooks that need it

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --all-groups
        uv pip install pre-commit

    - name: Run pre-commit on all files
      run: |
        # Run specific pre-commit hooks that are stable
        uv run pre-commit run trailing-whitespace --all-files --show-diff-on-failure
        uv run pre-commit run end-of-file-fixer --all-files --show-diff-on-failure
        uv run pre-commit run check-yaml --all-files --show-diff-on-failure || true
        uv run pre-commit run check-added-large-files --all-files --show-diff-on-failure
        uv run pre-commit run check-toml --all-files --show-diff-on-failure
        uv run pre-commit run check-json --all-files --show-diff-on-failure
        uv run pre-commit run check-merge-conflict --all-files --show-diff-on-failure
        uv run pre-commit run uv-lock --all-files --show-diff-on-failure
        uv run pre-commit run ruff --all-files --show-diff-on-failure
        uv run pre-commit run ruff-format --all-files --show-diff-on-failure
        uv run pre-commit run yamlfmt --all-files --show-diff-on-failure
        uv run pre-commit run yamllint --all-files --show-diff-on-failure
        uv run pre-commit run shellcheck --all-files --show-diff-on-failure
        uv run pre-commit run actionlint --all-files --show-diff-on-failure

    - name: Run Trufflehog secret detection
      run: |
        echo "Running Trufflehog secret detection..."
        uv run pre-commit run trufflehog --all-files --show-diff-on-failure


  dependency-check:
    name: Dependency analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --all-groups
        uv pip install deptry

    - name: Run deptry
      run: |
        echo "Running deptry dependency analysis..."
        uv run deptry src --config pyproject.toml

    - name: Check for dependency issues
      if: failure()
      run: |
        echo "❌ Dependency issues found! Please fix them before merging."
        echo "Run 'uv run deptry src' locally to see the issues."

  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --all-groups
        uv pip install pre-commit

    - name: Run ruff linter
      run: |
        echo "Running ruff linter..."
        uv run pre-commit run ruff --all-files --show-diff-on-failure

    - name: Check code formatting
      run: |
        echo "Checking code formatting with ruff..."
        uv run pre-commit run ruff-format --all-files --show-diff-on-failure

    - name: Run mypy type checker
      run: |
        echo "Running mypy type checker..."
        uv run pre-commit run mypy --all-files --show-diff-on-failure

  lock-file-check:
    name: Check lock file
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Verify lock file is up-to-date
      run: |
        echo "Verifying uv.lock is up-to-date..."
        uv lock --locked

    - name: Check for lock file changes
      run: |-
        if git diff --exit-code uv.lock; then
          echo "✅ Lock file is up-to-date"
        else
          echo "❌ Lock file is out of date! Run 'uv lock' locally and commit the changes."
          exit 1
        fi
