name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      run-super-linter:
        description: 'Run Super Linter in addition to regular checks'
        required: false
        type: boolean
        default: false

env:
  UV_CACHE_DIR: /tmp/.uv-cache
  RUN_SUPER_LINTER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run-super-linter == 'true' || 'false' }}

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for pre-commit hooks that need it

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --dev
        uv pip install pre-commit

    - name: Run pre-commit on all files
      run: uv run pre-commit run --all-files --show-diff-on-failure

  dependency-check:
    name: Dependency analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --dev
        uv pip install deptry

    - name: Run deptry
      run: |
        echo "Running deptry dependency analysis..."
        uv run deptry src --config pyproject.toml

    - name: Check for dependency issues
      if: failure()
      run: |
        echo "❌ Dependency issues found! Please fix them before merging."
        echo "Run 'uv run deptry src' locally to see the issues."
        echo "❌ Dependency issues found! Please fix them before merging."
        echo "Run 'uv run deptry src' locally to see the issues."

  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --locked --all-extras --dev

    - name: Run ruff linter
      run: |
        echo "Running ruff linter..."
        uv run ruff check src/ tests/ --output-format=github
        echo "Running ruff linter..."
        uv run ruff check src/ tests/ --output-format=github

    - name: Check code formatting
      run: |
        echo "Checking code formatting with ruff..."
        uv run ruff format --check src/ tests/
        echo "Checking code formatting with ruff..."
        uv run ruff format --check src/ tests/

    - name: Run mypy type checker
      run: |
        echo "Running mypy type checker..."
        uv run mypy src/DHT/ --show-error-codes --pretty
        echo "Running mypy type checker..."
        uv run mypy src/DHT/ --show-error-codes --pretty

  lock-file-check:
    name: Check lock file
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Verify lock file is up-to-date
      run: |
        echo "Verifying uv.lock is up-to-date..."
        uv lock --locked
        echo "Verifying uv.lock is up-to-date..."
        uv lock --locked

    - name: Check for lock file changes
      run: |
        if git diff --exit-code uv.lock; then
        echo "✅ Lock file is up-to-date"
        else
        echo "❌ Lock file is out of date! Run 'uv lock' locally and commit the changes."
        exit 1
        fi
        if git diff --exit-code uv.lock; then
          echo "✅ Lock file is up-to-date"
        else
          echo "❌ Lock file is out of date! Run 'uv lock' locally and commit the changes."
          exit 1
        fi

  super-linter:
    name: Super Linter (Optional)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run-super-linter == 'true' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Super Linter
      uses: super-linter/super-linter@v7.2.0
      env:
        VALIDATE_ALL_CODEBASE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main

        # Use our Python tools config
        PYTHON_BLACK_CONFIG_FILE: pyproject.toml
        PYTHON_RUFF_CONFIG_FILE: pyproject.toml
        PYTHON_MYPY_CONFIG_FILE: pyproject.toml

        # Quick mode - only essential linters
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_PYTHON_RUFF: true
        VALIDATE_YAML: true
        VALIDATE_GITHUB_ACTIONS: true
        VALIDATE_BASH: true

        # Minimal output
        SUPPRESS_POSSUM: true
        LOG_LEVEL: WARN
