name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for pre-commit hooks that need it

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --dev
        uv pip install pre-commit

    - name: Run pre-commit on all files
      run: uv run pre-commit run --all-files --show-diff-on-failure

  dependency-check:
    name: Dependency analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --dev
        uv pip install deptry

    - name: Run deptry
      run: |
        echo "Running deptry dependency analysis..."
        uv run deptry src --config pyproject.toml

    - name: Check for dependency issues
      if: failure()
      run: |
        echo "❌ Dependency issues found! Please fix them before merging."
        echo "Run 'uv run deptry src' locally to see the issues."

  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --locked --all-extras --dev

    - name: Run ruff linter
      run: |
        echo "Running ruff linter..."
        uv run ruff check src/ tests/ --output-format=github

    - name: Check code formatting
      run: |
        echo "Checking code formatting with ruff..."
        uv run ruff format --check src/ tests/

    - name: Run mypy type checker
      run: |
        echo "Running mypy type checker..."
        uv run mypy src/DHT/ --show-error-codes --pretty

  lock-file-check:
    name: Check lock file
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Verify lock file is up-to-date
      run: |
        echo "Verifying uv.lock is up-to-date..."
        uv lock --locked

    - name: Check for lock file changes
      run: |-
        if git diff --exit-code uv.lock; then
          echo "✅ Lock file is up-to-date"
        else
          echo "❌ Lock file is out of date! Run 'uv lock' locally and commit the changes."
          exit 1
        fi
