name: Lint All Files

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true  # Always cancel for lint jobs

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: |
        uv sync --all-extras
        uv pip install pre-commit

    - name: Run pre-commit on all files
      run: |
        source .venv/bin/activate
        pre-commit run --all-files --show-diff-on-failure

    - name: Run additional Python linters via pre-commit
      run: |-
        source .venv/bin/activate
        # Run individual pre-commit hooks for detailed output
        echo "Running ruff checks..."
        pre-commit run ruff --all-files || true

        echo "Running mypy type checking..."
        pre-commit run mypy --all-files || true

        echo "Running formatting checks..."
        pre-commit run ruff-format --all-files --show-diff-on-failure || true

        echo "Running dependency checks..."
        pre-commit run deptry --all-files || true
