name: Lint All Files

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: |
        uv sync --all-extras
        uv pip install pre-commit

    - name: Run pre-commit on all files
      run: |
        source .venv/bin/activate
        pre-commit run --all-files --show-diff-on-failure

    - name: Run additional Python linters
      run: |-
        source .venv/bin/activate
        # Run ruff with more comprehensive checks
        ruff check src/ tests/ --statistics

        # Run mypy with strict mode
        mypy src/ --strict --ignore-missing-imports || true

        # Check for security issues
        pip install bandit
        bandit -r src/ -ll || true
