name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
  # Run daily at 2 AM UTC
  - cron: '0 2 * * *'
  workflow_dispatch:

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for scanning all commits

    - name: Install gitleaks safely
      run: |
        echo "Installing gitleaks in /tmp to prevent overwriting project files..."
        bash .github/scripts/install-gitleaks-safe.sh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Run gitleaks scan
      run: |
        echo "Running gitleaks scan with custom config..."
        gitleaks detect --source . --config .gitleaks.toml --verbose --no-git

    - name: Run gitleaks on git history (allow failures for historical commits)
      run: |
        echo "Scanning git history for secrets..."
        gitleaks git --source . --config .gitleaks.toml --verbose || echo "Historical secrets found - please review"

    - name: Upload gitleaks report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.json
        retention-days: 30
